# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The full name of the customer', max_length=40, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The full name of the employee', max_length=40, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The date the task is done')),
                ('minutes', models.PositiveSmallIntegerField(help_text='Total minutes spend on task')),
                ('description', models.CharField(help_text='Description of the work done', max_length=200)),
                ('billable', models.BooleanField(default=False, help_text='Time is billable to customer')),
                ('invoiced', models.BooleanField(default=False, help_text='Time is billed to customer')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='WorkLog.Customer', verbose_name='customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='WorkLog.Employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'logbook',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The full name of the task', max_length=40, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'task',
            },
        ),
        migrations.AddField(
            model_name='logbook',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='WorkLog.Task', verbose_name='task'),
        ),
    ]
