# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='billable',
            field=models.BooleanField(default=False, help_text='Time is billable to customer', verbose_name='billable'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='date',
            field=models.DateField(help_text='The date the task is done', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='description',
            field=models.CharField(help_text='Description of the work done', max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='invoiced',
            field=models.BooleanField(default=False, help_text='Time is billed to customer', verbose_name='invoiced'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='minutes',
            field=models.PositiveSmallIntegerField(help_text='Total minutes spend on task', verbose_name='minutes'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
